#!/usr/bin/env python3
"""grip-sync: the two entry generators driven unmodified, plus this composition's
own glue clip table.

    python compositions/grip-sync/generate.py           # writes the three documents
    python compositions/grip-sync/generate.py --check   # asserts the prefab's silent surface, writes nothing

Three documents, three builds, ONE FullController on the prefab root:

  object-sync/controller.yaml   the object-sync entry's generator at CONFIG
                                `objects: [{Prop, full}]`, `mountPath "ObjectSync"`
                                (the nested sync rig's GO name under the root);
                                default rigSeed, so the nested rig is the entry's
                                own committed root prefab.
  readout/controller.yaml       absolute-grip-prop's readout document, emitted by
                                its generator unmodified, then every scene-binding
                                path prefixed with the nested entry's mount
                                (`Prop/AbsoluteGripProp/`) — a textual deviation
                                after the emit, the same shape the cell prefix
                                below takes. The entry generator has no mount
                                knob and this composition does not add one.
  controller.yaml               the glue (hand-authored graph above the marker;
                                the clip table below it is emitted here).

Why one component: the glue reads the sync build's sealed `OS/Ready` and the
readout's `Palm/*` AAPs. One FullController prefixes every controller it merges
identically, so those names unify with nothing published beyond the sync
build's own derived `globalParams`. Controller order in that component is
load-bearing: the glue sits FIRST in both the controllers list and the prms
list, so its `ObjectSync/Enable` declaration (default 1) wins the first-wins
parameter merge in each (controller.yaml's header owns the mechanism; --check
pins both orders). The readout sits between; it declares no name the other two
declare, so its position is free and is not pinned.

THE GLUE CLIP TABLE
-------------------
Cell bindings are read live from ../../absolute-grip-prop/controller.yaml's clip
table at emit time under PREFIX; CLIPS maps each glue clip to an entry clip by
NAME. Freezing a cell value here forks the entry (CONVENTIONS.md §compositions/).
The only literals here are glue-side: GLUE_KEYS, VALUE_SETS, the dwells, the
two carves and the per-clip notes.

Two carves, and only two, depart from the cell's values:

  GP_CARVE     grab-sync's: GrabPosition weights (1,0) in the word states, so the
               parked cell root rides the word through the repointed Display
               (../../grab-prop/README.md §How it works sanctions the repoint).
  ROTOR_CARVE  this composition's own: `Container/Rotor` gains a fourth source,
               `ObjectSync/Sync`, and in the word states the clip writes
               `Rotor.m_Enabled 1, source0 0, source3 1` (weights normalize by
               sum, so home must go to 0). Every other clip writes source3 = 0
               and the cell's own Rotor values. The cell freezes Rotor
               (m_Enabled 0) in acquire/latched/reacquire/settling/settled/
               released/dropped and re-enables it on the grip only in carry*,
               so on a remote the freeze holds the WORD's attitude from Synced
               through Grip Settled and the grip eases from it at Confirm —
               the park that replaces grab-sync's drag-heading park, with no
               second writer on Rotor (Damped's rotation smoother is unbound
               and always chases Rotor). This is the first composition to add a
               source inside the cell subtree; the capture edge
               (Container <- SourcePosition) is hierarchy-authored and outranks
               it, and the new ring's stale edges are measured, not inherited
               (README §Verifying it).
"""

import importlib.util
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PATTERNS = os.path.normpath(os.path.join(HERE, os.pardir, os.pardir))
SYNC_ENTRY = os.path.join(PATTERNS, "object-sync", "generate.py")
GRIP_ENTRY = os.path.join(PATTERNS, "absolute-grip-prop", "generate.py")
CELL_DOC = os.path.join(PATTERNS, "absolute-grip-prop", "controller.yaml")
GLUE_DOC = os.path.join(HERE, "controller.yaml")
OUT_SYNC = os.path.join(HERE, "object-sync", "controller.yaml")
OUT_READOUT = os.path.join(HERE, "readout", "controller.yaml")

# The nested GO names under the composition root — hand-maintained pairings the
# emitted bindings prefix and --check reads back off the prefab.
MOUNT = "ObjectSync"
CELL_MOUNT = "AbsoluteGripProp"
PREFIX = f"Prop/{CELL_MOUNT}/"

BEGIN = "  # --- BEGIN GENERATED by generate.py: cell bindings from absolute-grip-prop, glue from VALUE_SETS."
END = "  # --- END GENERATED"


def load(path, name):
    if not os.path.exists(path):
        raise SystemExit(f"REFUSE: {path} is missing — this composition drives that "
                         "entry's generator and cannot emit without it.")
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def sync_config(mod):
    cfg = dict(mod.CONFIG)
    cfg["objects"] = [{"name": "Prop", "rotation": "full"}]
    cfg["mountPath"] = MOUNT
    return cfg


# ================================================================ readout ===
def readout_text(grip):
    """The entry's readout document with every scene-binding path under PREFIX.
    Scene bindings are the quoted keys in `clips:`; parameter keys are bare.
    Refuses on a quoted key outside the entry's tip subtree, which would mean the
    entry grew a binding this prefix rule does not know."""
    text = grip.emit_readout()
    head, sep, clips = text.partition("\nclips:\n")
    if not sep:
        raise SystemExit("REFUSE: the readout document has no clips: block")
    bad = sorted({k for k in re.findall(r'"([^"]+)"', clips)
                  if not k.startswith("GrabPosition/")})
    if bad:
        raise SystemExit(f"REFUSE: readout scene bindings outside GrabPosition/: {bad[:5]}")
    clips = clips.replace('"GrabPosition/', f'"{PREFIX}GrabPosition/')
    n = clips.count(f'"{PREFIX}')
    head = head.replace(
        "# GENERATED by generate.py -- edit the generator, not this file.",
        "# GENERATED by compositions/grip-sync/generate.py from absolute-grip-prop's generator, "
        f"unmodified, then every scene binding prefixed {PREFIX} (the nested entry's mount).\n"
        "# Edit the ENTRY generator, never this file.", 1)
    return head + sep + clips, n


# =================================================================== glue ===
GP0 = PREFIX + "GrabPosition/VRCPositionConstraint.Sources.source0.Weight"
GP1 = PREFIX + "GrabPosition/VRCPositionConstraint.Sources.source1.Weight"
ROTOR = PREFIX + "Container/Rotor/VRCRotationConstraint"
ROTOR_EN, ROTOR_S0, ROTOR_S3 = (ROTOR + ".m_Enabled", ROTOR + ".Sources.source0.Weight",
                                ROTOR + ".Sources.source3.Weight")
WORD_STATES = {"acquire", "synced", "resume"}    # both carves land here, and only here

GLUE_KEYS = (
    "Prop/GameObject.m_IsActive",
    "Prop/Source/VRCPositionConstraint.Sources.source0.Weight",
    "Prop/Source/VRCPositionConstraint.Sources.source1.Weight",
    "Prop/Source/VRCPositionConstraint.Sources.source2.Weight",
    "Prop/Source/VRCRotationConstraint.Sources.source0.Weight",
    "Prop/Source/VRCRotationConstraint.Sources.source1.Weight",
    "Prop/Source/VRCRotationConstraint.Sources.source2.Weight",
    "Prop/Container/VRCPositionConstraint.Sources.source0.Weight",
    "Prop/Container/VRCPositionConstraint.Sources.source1.Weight",
    "Prop/Container/VRCRotationConstraint.Sources.source0.Weight",
    "Prop/Container/VRCRotationConstraint.Sources.source1.Weight",
    "Prop/Container/Display/GameObject.m_IsActive",
)
# grab-sync's sets minus its two DragBone keys; the canon for these digits.
VALUE_SETS = {
    "HOME-HIDE":    (1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0),
    "HOME-OFF":     (0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0),
    "HOME-SHOW":    (1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, None),
    "CARRY":        (1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1),
    "ACQUIRE-SHOW": (1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, None),
    "ACQUIRE-HIDE": (1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0),
    "SYNC":         (1, 0, 1, 0, 0, 1, 0, 0.1, 1, 0.2, 1, 1),
}

# The delayed show behind a re-enabled Prop. grab-sync's is 0.1 s for the y ring's
# 2-3 hops; the full ring adds the second marker arm and the Recon/ReconN aim
# pair, so this clip is longer. [EMPIRICAL: re-measure the flush frame count in
# play after any rig change — README §Verifying it]
ACQUIRE_LEN = 0.2
DISPLAY_DELAY = "{ tangents: stepped, keys: [ [0, 0], [0.15, 1] ] }"

# [EMPIRICAL] Bridge: the full-rotation build's release-to-committed-word latency,
# 0.55 s measure cycle + ~0.07 s unpark + 0.70 s wire refresh ≈ 1.32 s worst
# case (object-sync/controller.yaml's header carries the terms), under
# grab-sync's proportional buffer (pulse + bridge ≈ 2.2 × worst case). Derived
# here, and it lands at grab-sync's figure because grab-sync sized against the
# entry root build's ~1.3 s too — coincidence of inputs, not a copy.
BRIDGE = 2.4

# (glue clip, cell clip, value set, dwell, note lines). Dwell None inherits the
# cell clip's length; a string names a derived dwell.
CLIPS = (
    ("timer", "timer", "HOME-HIDE", None,
     ("cell `timer` + HOME hidden  [EMPIRICAL: dwell = clip length]",)),
    ("disabled", "disabled", "HOME-OFF", None,
     ("cell `disabled` (the twelve receivers off for the stow dwell) + HOME hidden",)),
    ("anchored", "anchored", "HOME-SHOW", None,
     ("cell `anchored` + HOME visible; delayed show as grab-sync's (entered only from hidden states)",)),
    ("grip_acquire", "acquire", "CARRY", None,
     ("cell `acquire` (Arrive dwell = clip length; Grip Acquire polls on the same clip) + CARRY",)),
    ("grip_reacquire", "reacquire", "CARRY", None,
     ("cell `reacquire` (receiver stow, dwell = clip length) + CARRY",)),
    ("grip_latched", "latched", "CARRY", None,
     ("cell `latched` + CARRY",)),
    ("grip_settling", "settling", "CARRY", None,
     ("cell `settling` (fill = clip length) + CARRY",)),
    ("grip_settled", "settled", "CARRY", None,
     ("cell `settled` (timeout = clip length) + CARRY",)),
    ("grip_carryRP", "carryRP", "CARRY", None, ("cell `carryRP` + CARRY (Confirm dwell = clip length; Carry loops it)",)),
    ("grip_carryRN", "carryRN", "CARRY", None, ("cell `carryRN` + CARRY",)),
    ("grip_carryLP", "carryLP", "CARRY", None, ("cell `carryLP` + CARRY",)),
    ("grip_carryLN", "carryLN", "CARRY", None, ("cell `carryLN` + CARRY",)),
    ("grip_recheckRP", "recheckRP", "CARRY", None, ("cell `recheckRP` + CARRY (recheck dwell = clip length)",)),
    ("grip_recheckRN", "recheckRN", "CARRY", None, ("cell `recheckRN` + CARRY",)),
    ("grip_recheckLP", "recheckLP", "CARRY", None, ("cell `recheckLP` + CARRY",)),
    ("grip_recheckLN", "recheckLN", "CARRY", None, ("cell `recheckLN` + CARRY",)),
    ("released", "released", "CARRY", None,
     ("cell `released` (pulse verbatim, curves included) + CARRY  [EMPIRICAL: the entry's pulse]",)),
    ("dropped", "dropped", "CARRY", None,
     ("cell `dropped` + CARRY",)),
    ("waiting", "waiting", "HOME-HIDE", None,
     ("cell `waiting` + HOME hidden (fail-visible: never show at a guessed spot)",)),
    ("acquire", "dropped", "ACQUIRE-SHOW", "ACQUIRE",
     ("cell `dropped` + ACQUIRE (rigid word flush); GrabPosition (1,0); Rotor parked on the word",
      "[EMPIRICAL: delayed show = the full ring's flush]")),
    ("bridge", "dropped", "CARRY", "BRIDGE",
     ("cell `dropped` + CARRY  [EMPIRICAL: bridge timer = clip length; pulse+bridge = {RESUME} s]",)),
    ("synced", "dropped", "SYNC", None,
     ("cell `dropped` + SYNC (damped word); GrabPosition (1,0); Rotor parked on the word",)),
    ("resume", "dropped", "ACQUIRE-HIDE", "RESUME",
     ("cell `dropped` + ACQUIRE, hidden; GrabPosition (1,0); Rotor parked  [EMPIRICAL: dwell = pulse {PULSE} + bridge {BRIDGE}]",)),
    ("resume_grab", "acquire", "ACQUIRE-HIDE", 0.1,
     ("cell `acquire` (cell wakes, root frozen) + ACQUIRE, hidden — the cell populates behind a hidden prop",
      "[EMPIRICAL: dwell = clip length, reacquire's]")),
    ("reacquire", "acquire", "SYNC", 0.1,
     ("cell `acquire` (cell wakes, root frozen on the word) + SYNC glue  [EMPIRICAL: dwell = clip length]",)),
)


def _num(v):
    r = round(float(v), 4)
    return str(int(r)) if r == int(r) else str(r)


def _sec(v):
    return str(round(float(v), 4))


def parse_clips(path):
    """The bounded clip-table subset the entry uses: 2-space clip names, 4-space
    set:/curves:/length rows, 6-space quoted bindings. Values stay verbatim
    strings so a transcribed value is byte-exact; dict order is the entry's."""
    clips, cur, sect, started = {}, None, None, False
    for line in open(path, encoding="utf-8"):
        if re.match(r"^clips:", line):
            started, cur = True, None
            continue
        if not started:
            continue
        m = re.match(r"^  ([\w+-]+):", line)
        if m:
            cur, sect = m.group(1), None
            clips[cur] = {"set": {}, "curves": {}, "len": None}
            continue
        if cur is None:
            continue
        m = re.match(r"^    (?:length|seconds): ([\d.]+)", line)
        if m:
            clips[cur]["len"] = m.group(1)
            continue
        if re.match(r"^    set:", line):
            sect = "set"
            continue
        if re.match(r"^    curves:", line):
            sect = "curves"
            continue
        m = re.match(r'^      "([^"]+)": (.+?)\s*$', line)
        if m and sect:
            clips[cur][sect][m.group(1)] = m.group(2)
            continue
        if line.strip() and not line.lstrip().startswith("#"):
            # A row this bounded parser does not model would otherwise vanish from the emitted table
            # (a dwell dropping to one frame, a binding unwritten) with nothing failing anywhere.
            raise SystemExit(f"REFUSE: unparsed clip-table row in {os.path.basename(path)} under `{cur}`: {line.rstrip()}")
    return clips


def emit_clips(cell):
    pulse = float(cell["released"]["len"])
    dwells = {"BRIDGE": BRIDGE, "RESUME": pulse + BRIDGE, "ACQUIRE": ACQUIRE_LEN}
    out = []
    for name, src, setname, dwell, note in CLIPS:
        if src not in cell:
            raise SystemExit(f"REFUSE: absolute-grip-prop/controller.yaml has no clip `{src}` — "
                             f"`{name}` transcribes it. Reconcile CLIPS against the entry's table.")
        e = cell[src]
        vals = VALUE_SETS[setname]
        rows, curves = {GLUE_KEYS[0]: _num(vals[0])}, {}
        for k, v in e["set"].items():
            rows[PREFIX + k] = v
        for k, v in e["curves"].items():
            curves[PREFIX + k] = v
        if GP0 not in rows or GP1 not in rows:
            raise SystemExit(f"REFUSE: cell clip `{src}` does not write GrabPosition's two source weights — the GrabPosition carve has nothing to carve")
        if ROTOR_EN not in rows or ROTOR_S0 not in rows:
            raise SystemExit(f"REFUSE: cell clip `{src}` does not write Rotor's enable and home "
                             "weight — the Rotor carve has nothing to carve")
        rows[ROTOR_S3] = "0"
        if name in WORD_STATES:
            rows[GP0], rows[GP1] = "1", "0"
            rows[ROTOR_EN], rows[ROTOR_S0], rows[ROTOR_S3] = "1", "0", "1"
        for k, v in zip(GLUE_KEYS[1:], vals[1:]):
            if v is None:
                curves[k] = DISPLAY_DELAY
            else:
                rows[k] = _num(v)
        length = dwells[dwell] if isinstance(dwell, str) else dwell
        if length is None and e["len"]:
            length = float(e["len"])
        text = [t.format(PULSE=_sec(pulse), BRIDGE=_sec(BRIDGE), RESUME=_sec(pulse + BRIDGE))
                for t in note]
        head = f"  {name}:"
        out.append(head + " " * max(1, 18 - len(head)) + "# " + text[0])
        out.extend(" " * 18 + "# " + t for t in text[1:])
        if length is not None:
            out.append(f"    length: {_sec(length)}")
        out.append("    set:")
        out.extend(f'      "{k}": {v}' for k, v in rows.items())
        if curves:
            out.append("    curves:")
            out.extend(f'      "{k}": {v}' for k, v in curves.items())
    return out


def splice(path, begin, end, body):
    lines = open(path, encoding="utf-8").read().split("\n")
    bi = [i for i, l in enumerate(lines) if l == begin]
    ei = [i for i, l in enumerate(lines) if l == end]
    if len(bi) != 1 or len(ei) != 1 or bi[0] >= ei[0]:
        raise SystemExit(f"REFUSE: {os.path.basename(path)} must carry exactly one marker pair, "
                         f"in order — found {len(bi)} begin, {len(ei)} end.")
    out = lines[:bi[0] + 1] + body + lines[ei[0]:]
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out))
    return len(body)


# ================================================================== check ===
def prefab_docs(path):
    # A nested instance's transforms serialize as `--- !u!4 &<id> stripped` documents; keep them, the check resolves them.
    return [(int(m.group(1)), int(m.group(2)), m.group(3)) for m in re.finditer(
        r"^--- !u!(\d+) &(\d+)(?: stripped)?\n(.*?)(?=^--- |\Z)", open(path, encoding="utf-8").read(), re.M | re.S)]


def entry_prefab(rel):
    """(guid, {fileID: (own name, parent name)} over transforms, {component fileID: owner name})."""
    prefab = os.path.join(PATTERNS, rel)
    guid = re.search(r"guid: (\w+)", open(prefab + ".meta", encoding="utf-8").read()).group(1)
    docs = prefab_docs(prefab)
    go_name = {a: re.search(r"m_Name: (.*)", b).group(1).strip() for c, a, b in docs if c == 1 and "m_Name:" in b}
    owner = {a: go_name.get(int(re.search(r"m_GameObject: \{fileID: (\d+)", b).group(1)), "?")
             for c, a, b in docs if c in (4, 114) and "m_GameObject:" in b}
    father = {a: int(re.search(r"m_Father: \{fileID: (\d+)", b).group(1)) for c, a, b in docs if c == 4}
    transforms = {a: (owner[a], owner.get(father[a], "<root>")) for a in father}
    comps = {a: (owner[a], b) for c, a, b in docs if c == 114}
    return guid, transforms, comps, docs


def check():
    ok = True

    def assert_(cond, msg):
        nonlocal ok
        print(("  ok   " if cond else "  FAIL ") + msg)
        ok = ok and cond

    def meta_guid(rel):
        return re.search(r"guid: (\w+)", open(os.path.join(HERE, rel) + ".meta", encoding="utf-8").read()).group(1)

    sync = load(SYNC_ENTRY, "object_sync_generate")
    path = os.path.join(HERE, "GripSync.prefab")
    raw = open(path, encoding="utf-8").read()
    docs = prefab_docs(path)
    names = {a: re.search(r"m_Name: (.*)", b).group(1).strip() for c, a, b in docs if c == 1 and "m_Name:" in b}
    go_of = {a: int(m.group(1)) for c, a, b in docs for m in [re.search(r"m_GameObject: \{fileID: (\d+)\}", b)] if m}
    tf_of_go = {go_of[a]: a for c, a, b in docs if c == 4 and a in go_of}
    father = {a: int(re.search(r"m_Father: \{fileID: (\d+)\}", b).group(1)) for c, a, b in docs if c == 4 and "m_Father" in b}

    # A nested instance's transform appears here only as a stripped document naming its source fileID; resolve its
    # name through the entry prefab it came from.
    stripped = {a: re.search(r"m_CorrespondingSourceObject: \{fileID: (\d+), guid: (\w+)", b).groups()
                for c, a, b in docs if c == 4 and "m_GameObject" not in b and "m_CorrespondingSourceObject" in b}
    entry_names = {}   # (entry guid, entry transform fileID) -> node name; filled once the entry prefabs are read

    def owner(a):
        if a in stripped:
            fid, guid = int(stripped[a][0]), stripped[a][1]
            return entry_names.get((guid, fid))
        return names.get(go_of.get(a))

    # ---- the shared component: one, glue first in both lists, the seal, the ids.
    assert_(raw.count("class: FullController") == 1,
            f"exactly ONE FullController (found {raw.count('class: FullController')}) — a second un-unifies every shared name")
    fc = next((b for c, a, b in docs if c == 114 and "class: FullController" in b), "")
    g_glue, g_read, g_sync = (meta_guid("built/GripSync_Fx.controller"), meta_guid("readout/built/GripReadout_Fx.controller"),
                              meta_guid("object-sync/built/ObjectSync_Fx.controller"))
    ctrls = re.search(r"controllers:(.*?)prms:", fc, re.S)
    order = re.findall(r"guid: ([0-9a-f]{32})", ctrls.group(1)) if ctrls else []
    assert_(order and order[0] == g_glue and set(order) == {g_glue, g_read, g_sync} and len(order) == 3,
            f"controllers: the glue FIRST, then the readout and sync builds, three in all — got {order}")
    p_glue, p_read, p_sync = (meta_guid("built/GripSync_Fx_Parameters.asset"), meta_guid("readout/built/GripReadout_Fx_Parameters.asset"),
                              meta_guid("object-sync/built/ObjectSync_Fx_Parameters.asset"))
    prms = re.search(r"prms:(.*?)globalParams:", fc, re.S)
    porder = re.findall(r"guid: ([0-9a-f]{32})", prms.group(1)) if prms else []
    assert_(porder and porder[0] == p_glue and set(porder) == {p_glue, p_read, p_sync} and len(porder) == 3,
            f"prms: the glue params asset FIRST (the baked Enable default merges in prms order) — got {porder}")
    want_gp = sync.document(sync_config(sync))[1]["facts"]["globalParams"]
    blocks = re.findall(r"globalParams:\n((?:        - .+\n)+)", fc)
    got = [[ln.split("- ", 1)[1].strip().strip("'\"") for ln in b.splitlines()] for b in blocks]
    assert_(got == [want_gp], f"globalParams is exactly the sync build's derived list {want_gp} — got {got}")
    assert_("rootBindingsApplyToAvatar: 0" in fc, "rootBindingsApplyToAvatar 0 (basis: mount-root)")
    ids = re.findall(r"id: ([0-9a-f]{32}\|[^\n]*)", fc)
    assert_(ids and all(i.split("|", 1)[1].startswith("Packages/com.ryan6vrc.patterns/compositions/grip-sync/") for i in ids),
            f"every cached asset id names this composition under the package, never a venue ({len(ids)} ids)")

    # ---- the two nested instances: resolved by source guid, named, placed, customised by removal only.
    def instance(guid):
        return next(((a, b) for c, a, b in docs if c == 1001 and f"m_SourcePrefab: {{fileID: 100100000, guid: {guid}" in b), (None, ""))

    fc_go = int(re.search(r"m_GameObject: \{fileID: (\d+)\}", fc).group(1)) if fc else None
    root_tf = tf_of_go.get(fc_go)
    sync_guid, sync_tf, sync_comps, sync_docs = entry_prefab("object-sync/ObjectSync.prefab")
    sync_gos = {a: re.search(r"m_Name: (.*)", b).group(1).strip() for c, a, b in sync_docs if c == 1}
    cell_guid, cell_tf, cell_comps, cell_docs = entry_prefab("absolute-grip-prop/AbsoluteGripProp.prefab")
    entry_names.update({(sync_guid, a): nm for a, (nm, _p) in sync_tf.items()})
    entry_names.update({(cell_guid, a): nm for a, (nm, _p) in cell_tf.items()})
    s_id, s_inst = instance(sync_guid)
    c_id, c_inst = instance(cell_guid)
    assert_(s_inst and c_inst, "both entry prefabs are nested instances (object-sync root prefab, absolute-grip-prop)")

    def iname(inst):
        m = re.search(r"propertyPath: m_Name\s*\n\s*value: (.+)", inst)
        return m.group(1).strip() if m else None

    def iparent(inst):
        m = re.search(r"m_TransformParent: \{fileID: (\d+)\}", inst)
        return int(m.group(1)) if m else None

    assert_(iname(s_inst) == MOUNT and iparent(s_inst) == root_tf,
            f"the sync instance is named {MOUNT!r} directly under the component's GO (got {iname(s_inst)!r}, parent {iparent(s_inst)})")
    prop_tf = next((a for c, a, b in docs if c == 4 and owner(a) == "Prop" and father.get(a) == root_tf), None)
    assert_(prop_tf is not None and iname(c_inst) == CELL_MOUNT and iparent(c_inst) == prop_tf,
            f"the cell instance is named {CELL_MOUNT!r} under Prop, which hangs under the component's GO")

    def removed(inst):
        m = re.search(r"m_RemovedComponents:\n((?:    - \{fileID: .+\n)+)", inst)
        return set(int(x) for x in re.findall(r"fileID: (\d+)", m.group(1))) if m else set()

    def removed_gos(inst):
        m = re.search(r"m_RemovedGameObjects:\n((?:    - \{fileID: .+\n)+)", inst)
        return set(int(x) for x in re.findall(r"fileID: (\d+)", m.group(1))) if m else set()

    def comps_named(comps, cls, on=None):
        return {a for a, (o, b) in comps.items() if cls in b and (on is None or o == on)}

    # object-sync root prefab: its FullController, Toggle, ApplyDuringUpload and pin pair (root), the Drop toggle (Sync_Target).
    s_rm = removed(s_inst)
    want = {"FullController": comps_named(sync_comps, "class: FullController", "ObjectSync"),
            "root Toggle": comps_named(sync_comps, "class: Toggle", "ObjectSync"),
            "root ApplyDuringUpload": comps_named(sync_comps, "class: ApplyDuringUpload", "ObjectSync"),
            "root pin pair": {a for a, (o, b) in sync_comps.items() if o == "ObjectSync" and ("ParentPositionOffset" in b or "ScaleAtRest" in b)},
            "Sync_Target Drop toggle": comps_named(sync_comps, "class: Toggle", "Sync_Target")}
    for label, ids_ in want.items():
        assert_(ids_ and ids_ <= s_rm, f"sync instance removes the entry's {label} ({sorted(ids_)})")
    s_want = set().union(*want.values())
    assert_(s_rm == s_want, f"sync instance removes NOTHING beyond the declared set — extra: {sorted(s_rm - s_want)}")
    assert_(len(want["root pin pair"]) == 2, "the entry root carries exactly its pin pair (parent + scale)")
    # absolute-grip-prop: FullController, Toggle removed; Payload GO and the root FreezeToWorld GO removed; EditorOnly kept.
    c_rm, c_rmgo = removed(c_inst), removed_gos(c_inst)
    for label, ids_ in {"FullController": comps_named(cell_comps, "class: FullController", CELL_MOUNT),
                        "Toggle": comps_named(cell_comps, "class: Toggle", CELL_MOUNT)}.items():
        assert_(ids_ and ids_ <= c_rm, f"cell instance removes the entry's {label} ({sorted(ids_)})")
    cell_gos = {a: re.search(r"m_Name: (.*)", b).group(1).strip() for c, a, b in cell_docs if c == 1}
    for node in ("Payload", "FreezeToWorld"):
        gid = {a for a, n in cell_gos.items() if n == node}
        assert_(gid and gid <= c_rmgo, f"cell instance removes the entry's {node} GameObject ({sorted(gid)})")
    eo = {a for a, n in cell_gos.items() if n == "EditorOnly"}
    assert_(eo and not (eo & c_rmgo), "cell instance KEEPS EditorOnly (its TurnOff ApplyDuringUpload rides it)")
    c_want = comps_named(cell_comps, "class: FullController", CELL_MOUNT) | comps_named(cell_comps, "class: Toggle", CELL_MOUNT)
    assert_(c_rm == c_want, f"cell instance removes NO component beyond FullController + Toggle — extra: {sorted(c_rm - c_want)}")
    go_want = {a for a, n in cell_gos.items() if n in ("Payload", "FreezeToWorld")}
    assert_(c_rmgo == go_want, f"cell instance removes NO GameObject beyond Payload + FreezeToWorld — extra: {sorted(c_rmgo - go_want)}")

    # ---- the cell instance's modifications: exactly the declared set, parsed with a count guard.
    mod_re = re.compile(r"- target: \{fileID:\s+(\d+),\s+guid:\s+(\w+),\s+type:\s+3\}\s*\n"
                        r"      propertyPath: ([^\n]+)\n      value: ([^\n]*)\n"
                        r"      objectReference: \{fileID:\s+(\d+)(?:,\s+guid:\s+\w+,\s+type:\s+\d+)?\}")
    mods = mod_re.findall(c_inst)
    want_rows = c_inst.count("\n      propertyPath: ")
    assert_(len(mods) == want_rows, f"cell instance: the modification parser read every row ({len(mods)} of {want_rows})")
    by_node = {}
    for fid, guid, pp, val, ref in mods:
        if guid == cell_guid:
            by_node.setdefault(cell_comps.get(int(fid), (cell_tf.get(int(fid), (cell_gos.get(int(fid), "?"),))[0],))[0], []).append((pp, val, ref))
    allowed = {
        "GrabBone": lambda pp: pp == "parameter",
        "GrabPosition": lambda pp: pp.startswith("Sources.source0.SourceTransform"),
        "Rotor": lambda pp: pp.startswith("Sources.source3") or pp == "Sources.totalLength",
        CELL_MOUNT: lambda pp: pp in ("m_Name", "m_RootOrder") or pp.startswith(("m_Local", "m_IsActive")),
    }
    stray = {n: [pp for pp, _, _ in rows if not allowed.get(n, lambda p: False)(pp)] for n, rows in by_node.items()}
    stray = {n: p for n, p in stray.items() if p}
    assert_(not stray, f"cell instance carries no modification beyond the declared overrides — stray: {stray}")
    grab = dict((pp, val) for pp, val, _ in by_node.get("GrabBone", []))
    assert_(grab.get("parameter") == "Grab", f"the grab physbone's parameter is `Grab` (got {grab.get('parameter')!r})")
    gp = {pp: ref for pp, _, ref in by_node.get("GrabPosition", [])}
    cont_tf = next((a for c, a, b in docs if c == 4 and owner(a) == "Container" and father.get(a) == prop_tf), None)
    disp = next((a for c, a, b in docs if c == 4 and owner(a) == "Display" and father.get(a) == cont_tf), None)
    assert_(gp.get("Sources.source0.SourceTransform") == str(disp) and disp is not None,
            "GrabPosition source0 is repointed at Prop/Container/Display (grab-prop's two-source repoint)")
    rot = {pp: (val, ref) for pp, val, ref in by_node.get("Rotor", [])}
    # Sync lives inside the nested sync instance, so its transform is a stripped/host reference; resolve by the objectReference target's name.
    ref_name = {str(a): owner(a) for c, a, b in docs if c == 4}
    assert_(rot.get("Sources.totalLength", ("", ""))[0] == "4", "Rotor's source list length is 4 (a slot past the length is a client no-op)")
    assert_(ref_name.get(rot.get("Sources.source3.SourceTransform", ("", ""))[1]) == "Sync",
            f"Rotor source3 targets ObjectSync/Sync (got {ref_name.get(rot.get('Sources.source3.SourceTransform', ('', ''))[1])!r})")
    assert_(rot.get("Sources.source3.Weight", ("", ""))[0] in ("0", ""), "Rotor source3 ships at weight 0 — no override row, so the array-fill default (the clips select it)")
    for pp in ("Sources.source3.ParentPositionOffset", "Sources.source3.ParentRotationOffset"):
        assert_(not any(k.startswith(pp) and float(v) != 0 for k, (v, _) in rot.items()), f"Rotor source3 has a zero {pp.split('.')[-1]}")
    sp = [a for a, (nm, par) in cell_tf.items() if nm == "SourcePosition"]
    assert_(len(sp) == 1 and cell_tf[sp[0]][1] == "Container", "cell: SourcePosition is a child of Container (the capture edge)")

    # ---- the composition's own nodes: Sync_Target measures Prop/Source; the mux and damper sources; the root pin at zero, disabled.
    def sources(b):
        return [(ref_name.get(m.group(1), m.group(1)), float(m.group(2))) for m in
                re.finditer(r"SourceTransform: \{fileID: (\d+)[^}]*\}\n\s+Weight: ([-0-9.e]+)", b) if m.group(1) != "0"]

    # Sync_Target's constraint is inside the nested sync instance; its added source is an instance modification.
    st_mods = {pp: (val, ref) for fid, guid, pp, val, ref in mod_re.findall(s_inst)
               if guid == sync_guid and sync_comps.get(int(fid), ("",))[0] == "Sync_Target"}
    s_mods = mod_re.findall(s_inst)
    s_rows = s_inst.count("\n      propertyPath: ")
    assert_(len(s_mods) == s_rows, f"sync instance: the modification parser read every row ({len(s_mods)} of {s_rows})")
    s_by_node = {}
    for fid, guid, pp, val, ref in s_mods:
        if guid == sync_guid:
            s_by_node.setdefault(sync_comps.get(int(fid), (sync_tf.get(int(fid), (sync_gos.get(int(fid), "?"),))[0],))[0], []).append(pp)
    s_allowed = {"Sync_Target": lambda pp: pp.startswith("Sources.source0.") or pp == "Sources.totalLength",
                 MOUNT: lambda pp: pp in ("m_Name", "m_RootOrder") or pp.startswith(("m_Local", "m_IsActive"))}
    s_stray = {nd: [pp for pp in pps if not s_allowed.get(nd, lambda q: False)(pp)] for nd, pps in s_by_node.items()}
    s_stray = {nd: q for nd, q in s_stray.items() if q}
    assert_(not s_stray, f"sync instance carries no modification beyond Sync_Target's one source — stray: {s_stray}")
    assert_(st_mods.get("Sources.totalLength", ("", ""))[0] == "1"
            and st_mods.get("Sources.source0.Weight", ("", ""))[0] == "1"
            and ref_name.get(st_mods.get("Sources.source0.SourceTransform", ("", ""))[1]) == "Source",
            "Sync_Target's one source is Prop/Source (static, weight 1)")
    for node, cls, want_src in (("Source", "PositionAtRest", ["Damped", "Sync", "Offset"]),
                                ("Source", "RotationAtRest", ["Damped", "Sync", "Offset"]),
                                ("Container", "PositionAtRest", ["Source", "Container"]),
                                ("Container", "RotationAtRest", ["Source", "Container"])):
        b = next((b for c, a, b in docs if c == 114 and cls in b and "AimVector" not in b and owner(a) == node
                  and father.get(tf_of_go.get(go_of[a])) in (prop_tf, next((x for c2, x, b2 in docs if c2 == 4 and owner(x) == "Source"), None))), "")
        got_src = [n for n, _ in sources(b)]
        assert_(got_src == want_src, f"{node} {cls.replace('AtRest', '')} constraint sources {want_src} (got {got_src})")
    root_cons = [b for c, a, b in docs if c == 114 and go_of.get(a) == fc_go and ("ParentPositionOffset" in b or "ScaleAtRest" in b)]
    assert_(len(root_cons) == 2 and all("m_Enabled: 0" in b for b in root_cons), "the root pin pair ships disabled (ApplyDuringUpload enables it)")
    offs = [float(x) for b in root_cons for t in re.findall(r"Parent(?:Position|Rotation)Offset: \{x: ([-0-9.e]+), y: ([-0-9.e]+), z: ([-0-9.e]+)\}", b) for x in t]
    assert_(root_cons and all(o == 0 for o in offs), "the root pin's source offsets are all zero (the client scales a pin offset by avatar scale)")
    scale_offs = [float(x) for b in root_cons for t in re.findall(r"ScaleOffset: \{x: ([-0-9.e]+), y: ([-0-9.e]+), z: ([-0-9.e]+)\}", b) for x in t]
    assert_(len(scale_offs) == 3 and all(o == 1 for o in scale_offs), "the scale pin's ScaleOffset is identity (1,1,1)")
    assert_(any(c == 114 and go_of.get(a) == fc_go and "class: ApplyDuringUpload" in b for c, a, b in docs), "an ApplyDuringUpload on the ROOT GameObject enables the pin at build")

    # ---- the glue's Palm/* declarations equal the entry glue's, read live.
    def palm_block(p):
        return [l.rstrip() for l in open(p, encoding="utf-8") if re.match(r"^  Palm/", l)]
    assert_(palm_block(GLUE_DOC) == palm_block(CELL_DOC),
            "controller.yaml declares Palm/* exactly as absolute-grip-prop's glue does (a type/default mismatch merges first-wins silently)")
    return 0 if ok else 1


def main():
    if "--check" in sys.argv:
        sys.exit(check())
    sync = load(SYNC_ENTRY, "object_sync_generate")
    grip = load(GRIP_ENTRY, "absolute_grip_prop_generate")

    cell = parse_clips(CELL_DOC)
    n = splice(GLUE_DOC, BEGIN, END, emit_clips(cell))
    print(f"wrote controller.yaml: {len(CLIPS)} clips, {n} lines emitted "
          f"({len(cell['dropped']['set'])} cell bindings + {len(GLUE_KEYS)} glue + Rotor source3 per clip)")

    text, nprefixed = readout_text(grip)
    os.makedirs(os.path.dirname(OUT_READOUT), exist_ok=True)
    with open(OUT_READOUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print(f"wrote readout/controller.yaml: {nprefixed} scene bindings prefixed {PREFIX}")

    text, f = sync.document(sync_config(sync))
    facts = f["facts"]
    os.makedirs(os.path.dirname(OUT_SYNC), exist_ok=True)
    with open(OUT_SYNC, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print(f"wrote object-sync/controller.yaml: {len(f['layers'])} layers, {len(f['clips'])} clips, "
          f"{facts['wireBits']} wire bits, {facts['payloadBits']} payload bits, {facts['batchCount']} batches, "
          f"~{facts['cycleSeconds']:.3f}s refresh @60fps")


if __name__ == "__main__":
    main()
